### ISSUE TITLE
[Request] Allow user to change webserver port in use

### ISSUE THREAD

**Issue by BobOkisama** [ryjo1026/PlexLandingPage#1]
Would like an easy way to change the web server listening port.

**Comment by ryjo1026** [comment]
I don't really know what you mean. I just have ways to change the links to your various other sites in script.js. You should be able to change what port the site is presented on by changing the configuration in your web server (nginx/apache).

**Comment by BobOkisama** [comment]
Ahh, so I need to have my own install of apache then configure it to go to
the page. Ok, that makes sense.
For the other I would like to be able to change the full url. I do not use
domain.com:port/whatever I use subdomains so like plex.boboki.com:1234 and
requests.boboki.com:2345

**Comment by ryjo1026** [comment]
Yep answered that in #2
