### ISSUE TITLE
[Request] Allow different full URLs to other apps

### ISSUE THREAD

**Issue by BobOkisama** [ryjo1026/PlexLandingPage#2]
You currently have it setup to a base url and then you can add a port and /whatever on the end, can we have the ability to just put full urls for those of us that use subdomains?

**Comment by ryjo1026** [comment]
I just have that piece set up in a way that's convenient to me. If you don't have a common base URL, you have two options:

1. You can delete script.js and its linking in index.html and just write links within the <a> tags on the buttons.

2. You can modify script.js to make it look like this 
```javascript

$( document ).ready(function(){
  // Write Links
  $("#access-link").attr('href','LINK TO ACCESS PAGE HERE');
  $("#requests-link").attr('href','LINK TO REQUESTS PAGE HERE');
})
```

**Comment by BobOkisama** [comment]
Either will work fine for me, thanks!
