### ISSUE TITLE
Create a Docker image for this project

### ISSUE THREAD

**Issue by ryjo1026** [ryjo1026/PlexLandingPage#8]
Need to create a Dockerfile that at minimum:
- [x] Installs nginx/apache
- [x] Properly configures the server
- [x] Pulls the git repo into the proper directory
- [x] Installs npm dependencies and 
- [x] Puts www/ in a volume for easy editing

**Comment by dalekseevs** [comment]
Would love for this to happen. +1

**Comment by ryjo1026** [comment]
Nope, just focused on other things ATM. Should be closed with PR #22
